# Create a program that will play the 'cows and bulls' game with the user. The game works
# like this:
#
# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every
# digit that the user guessed correctly in the correct place, they have a 'cow'. For
# every digit the user guessed correctly in the wrong place is a 'bull.' Every time the
# user makes a guess, tell them how many 'cows' and 'bulls' they have. Once the user
# guesses the correct number, the game is over. Keep track of the number of guesses the
# user makes throughout the game and tell the user at the end.
#
# Say the number generated by the computer is 1038. An example interaction could look like
# this:
#
#   Welcome to the Cows and Bulls Game!
#   Enter a number:
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1256
#   1 cow, 1 bull

# Until the user guesses the number.


import random

number = str(random.randint(1000, 9999))  # random 4 digit number
heylist = []
for i in number:
    heylist.append(i)

guessin = 0
while True:
    while True:
        playnum = raw_input("Guess a four-digit number: ")
        if len(playnum) == 4:
            try:
                val = int(playnum)
            except ValueError:
                print("That's not a number!")
            else:
                break
        else:
            print "Input must be a four-digit number!"
    playlist = []
    for x in playnum:
        playlist.append(x)
    cows = 0
    bulls = 0
    heylist = []
    for i in number:
        heylist.append(i)
    if playnum == number:
        print "You win!"
        break
    else:
        for x in range(0, 4):
            if playlist[x] == heylist[x]:
                heylist[x] = 'moo'
                cows += 1


        for x in range(0, 4):
            if heylist[x] in playlist:
                bulls += 1
                heylist[x] = "angery"


        if cows == 1 and bulls == 1:
            print "1 cow, 1 bull"
        elif cows == 1:
            print "1 cow, " + str(bulls) + " bulls"
        elif bulls == 1:
            print str(cows) + " cows, 1 bull"
        else:
            print str(cows) + " cows, " + str(bulls) + " bulls"
        guessin += 1

if guessin == 1:
    print "Wow, it only took you one try to find the number."
else:
    print "It took you " + str(guessin) + " tries to guess " + str(number) + ", the correct number."
