# Create a program that will play the 'cows and bulls' game with the user. The game works
# like this:
#
# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every
# digit that the user guessed correctly in the correct place, they have a 'cow'. For
# every digit the user guessed correctly in the wrong place is a 'bull.' Every time the
# user makes a guess, tell them how many 'cows' and 'bulls' they have. Once the user
# guesses the correct number, the game is over. Keep track of the number of guesses the
# user makes throughout the game and tell the user at the end.
#
# Say the number generated by the computer is 1038. An example interaction could look like
# this:
#
#   Welcome to the Cows and Bulls Game!
#   Enter a number:
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1256
#   1 cow, 1 bull

# Until the user guesses the number.


import random
number = str(random.randint(1000,9999)) #random 4 digit number
print number
numlist = []
for i in number:
    numlist.append(i)

guesses = 0
while True:
    cows = 0
    bulls = 0
    counter = 0
    playnum = raw_input("Guess a 4-digit number: ")
    guesses += 1
    playlist = []
    for x in playnum:
        playlist.append(x)
    if playnum == number:
        print "You win!"
        break
    else:
        cowlist = []
        for digit in playlist:
            if digit == numlist[counter]:
                cows += 1
                cowlist.append(digit)
            elif digit in numlist and digit not in cowlist:
                bulls += 1
            counter += 1
    if cows == 1 and bulls == 1:
        print "1 cow, 1 bulls"
    elif cows == 1:
        print "1 cow, " + str(bulls) + " bulls"
    elif bulls == 1:
        print str(cows) + " cows, 1 bull"
    else:
        print str(cows) + " cows, " + str(bulls) + " bulls"

if guesses == 1:
    print "Wow, it only took you one try to find the number."
else:
    print "It took you " + str(guesses) + " tries to guess " + str(number) + ", the correct number."
